/**
 * Copyright (c) 2016 - 2018, Nordic Semiconductor ASA
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form, except as embedded into a Nordic
 *    Semiconductor ASA integrated circuit in a product or a software update for
 *    such product, must reproduce the above copyright notice, this list of
 *    conditions and the following disclaimer in the documentation and/or other
 *    materials provided with the distribution.
 *
 * 3. Neither the name of Nordic Semiconductor ASA nor the names of its
 *    contributors may be used to endorse or promote products derived from this
 *    software without specific prior written permission.
 *
 * 4. This software, with or without modification, must only be used with a
 *    Nordic Semiconductor ASA integrated circuit.
 *
 * 5. Any software provided in binary form under this license must not be reverse
 *    engineered, decompiled, modified and/or disassembled.
 *
 * THIS SOFTWARE IS PROVIDED BY NORDIC SEMICONDUCTOR ASA "AS IS" AND ANY EXPRESS
 * OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY, NONINFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL NORDIC SEMICONDUCTOR ASA OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */
/** @file
 *
 * @defgroup wake_on_nfc_example_main main.c
 * @{
 * @ingroup wake_on_nfc_example
 * @brief Wake on NFC Example Application main file.
 *
 */

#include <stdbool.h>
#include <stdint.h>
#include "app_timer.h"
#include "nrf_delay.h"
#include "nrf_gpio.h"
#include "nrf_drv_clock.h"
#include "bsp.h" 
#include "nrf.h"
#include "nrf_sdh.h"
#include "nrf_sdh_soc.h"
#include "sdk_errors.h"

#include "nrf_log.h"
#include "nrf_log_ctrl.h"
#include "nrf_log_default_backends.h"
#include "nrf_pwr_mgmt.h"

#define BTN_ID_SLEEP                0 /**< ID of button used to put the application into sleep mode. */
#define BTN_ID_WAKEUP				1 /**< ID of button used to put the application exit sleep mode. */
#define BTN_ID_POWEROFF				2 /**< ID of button used to put the application exit sleep mode. */
#define BTN_ID_POWERON				3 /**< ID of button used to put the application exit sleep mode. */

#define APP_TICK_EVENT_INTERVAL     APP_TIMER_TICKS(500) /**< 500 miliseconds tick event interval in timer tick units. */

APP_TIMER_DEF(m_tick_timer);             /**< Timer used to toggle LED state. */

static volatile bool m_system_off_mode_on = false; /**< Indicates if the application should go into System OFF mode. */


/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by BSP.
 */
static void bsp_event_handler(bsp_event_t event)
{
	ret_code_t err_code = NRF_SUCCESS;

	switch (event)
	{
	case BSP_EVENT_SLEEP:
		NRF_LOG_INFO("bsp_event_handler: BSP_EVENT_SLEEP.");
		NRF_LOG_FLUSH();
	
		err_code = app_timer_stop(m_tick_timer);
		APP_ERROR_CHECK(err_code);

		bsp_board_led_off(BSP_BOARD_LED_1);

		m_system_off_mode_on = true;
		break;

	case BSP_EVENT_WAKEUP:
		NRF_LOG_INFO("bsp_event_handler: BSP_EVENT_WAKEUP.");
		NRF_LOG_FLUSH();
		
		err_code = app_timer_start(m_tick_timer, APP_TICK_EVENT_INTERVAL, NULL);
		APP_ERROR_CHECK(err_code);

		m_system_off_mode_on = false;
		break;

	case BSP_EVENT_SYSOFF:
		NRF_LOG_INFO("bsp_event_handler: BSP_EVENT_SYSOFF.");
		NRF_LOG_FLUSH();
		
		bsp_board_led_off(BSP_BOARD_LED_0);
		bsp_board_led_off(BSP_BOARD_LED_1);
		//sd_power_system_off();
		NRF_POWER-> SYSTEMOFF = 1;
		break;

	default:
		break;
	}
}

static void idle_state_handle(void)
{
    NRF_LOG_FLUSH();
    nrf_pwr_mgmt_run();
}

static void log_init(void)
{
    ret_code_t err_code = NRF_LOG_INIT(NULL);
    APP_ERROR_CHECK(err_code);

    NRF_LOG_DEFAULT_BACKENDS_INIT();
}


/**
 * @brief 500 miliseconds tick handler for changing the LED state.
 */
static void app_tick_handler(void * p_context)
{
	NRF_LOG_INFO("app_tick_handler.");
	NRF_LOG_FLUSH();

    bsp_board_led_invert(BSP_BOARD_LED_1);
}


/**@brief Function for the Timer and BSP initialization.
 */
static void utils_setup(void)
{
	ret_code_t err_code;

	log_init();

	err_code = nrf_pwr_mgmt_init();
	APP_ERROR_CHECK(err_code);

	err_code = nrf_drv_clock_init();
	APP_ERROR_CHECK(err_code);
	nrf_drv_clock_lfclk_request(NULL);

	err_code = app_timer_init();
	APP_ERROR_CHECK(err_code);

	err_code = bsp_init(BSP_INIT_LEDS | BSP_INIT_BUTTONS, bsp_event_handler);
	APP_ERROR_CHECK(err_code);

	err_code = bsp_event_to_button_action_assign(BTN_ID_SLEEP, BSP_BUTTON_ACTION_RELEASE, BSP_EVENT_SLEEP);
	APP_ERROR_CHECK(err_code);
	err_code = bsp_event_to_button_action_assign(BTN_ID_WAKEUP, BSP_BUTTON_ACTION_RELEASE, BSP_EVENT_WAKEUP);
	APP_ERROR_CHECK(err_code);
	err_code = bsp_event_to_button_action_assign(BTN_ID_POWEROFF, BSP_BUTTON_ACTION_RELEASE, BSP_EVENT_SYSOFF);
	APP_ERROR_CHECK(err_code);
	err_code = bsp_event_to_button_action_assign(BTN_ID_POWERON, BSP_BUTTON_ACTION_RELEASE, BSP_EVENT_WAKEUP);
	APP_ERROR_CHECK(err_code);

	err_code = app_timer_create(&m_tick_timer,
	                            APP_TIMER_MODE_REPEATED,
	                            app_tick_handler);
	APP_ERROR_CHECK(err_code);

	// Schedule a timeout event every 500 miliseconds
	err_code = app_timer_start(m_tick_timer, APP_TICK_EVENT_INTERVAL, NULL);
	APP_ERROR_CHECK(err_code);
}


/**
 * @brief Function for application main entry.
 */
int main(void)
{
	utils_setup();

	NRF_LOG_INFO("main started.");
	NRF_LOG_FLUSH();

	// Turn on LED to indicate that the device entered System ON mode.
	bsp_board_led_on(BSP_BOARD_LED_0);

	while (true)
	{
		nrf_pwr_mgmt_run();
	}
}


/** @} */
